# -*- coding: utf-8 -*-
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# MantPro - Sistema de Mantenimiento Preventivo
# Copyright (C) 2026 AnabasaSoft <anabasasoft@gmail.com>
#
# Este programa es software libre: puedes redistribuirlo y/o modificarlo bajo
# los términos de la Licencia Pública General Affero de GNU publicada por la
# Free Software Foundation, ya sea la versión 3 de la Licencia o (a tu
# elección) cualquier versión posterior.
#
# Este programa se distribuye con la esperanza de que sea útil, pero SIN
# NINGUNA GARANTÍA; ni siquiera la garantía implícita de COMERCIABILIDAD o
# IDONEIDAD PARA UN PROPÓSITO PARTICULAR. Consulta la Licencia Pública
# General Affero de GNU para más detalles.
#
# Deberías haber recibido una copia de la Licencia Pública General Affero de
# GNU junto con este programa. Si no, consulta <https://www.gnu.org/licenses/>.


# ==========================================
# SISTEMA DE IDIOMAS - MantPro (Escritorio)
# ==========================================
# Cómo añadir un idioma nuevo:
#   1. Copia el bloque "es" o "en" entero y tradúcelo.
#   2. Añade su entrada en IDIOMAS_DISPONIBLES.
#   3. Ya aparece automáticamente en el menú Herramientas > Idioma.
#
# Cómo usar una clave nueva en el código:
#   - Añade la clave en TODOS los idiomas (si falta en alguno, se
#     mostrará la clave en español como respaldo automático).
#   - Donde antes tenías texto literal, usa t("tu_clave").

IDIOMAS_DISPONIBLES = [
    ("es", "Español"),
    ("en", "English"),
    ("eu", "Euskara"),
]

TRADUCCIONES = {
    "es": {
        # --- Listas, Estados y Notificaciones ---
        "hdr_fecha": "FECHA",
        "hdr_descripcion": "DESCRIPCIÓN",
        "hdr_tags": "TAGS",
        "hdr_foto_antes": "FOTO ANTES",
        "hdr_foto_despues": "FOTO DESPUÉS",
        "msg_dia_no_laborable": "--- Día no laborable ---",
        "msg_nada_registrado": "--- Nada registrado ---",
        "msg_nada": "--- Nada ---",
        "msg_sin_detalles": "Sin detalles",
        "msg_no_hay_pendientes": "No hay tareas pendientes",
        "msg_no_hay_avisos": "No hay avisos",
        "msg_sin_historial": "Sin historial visible",
        "msg_sin_registros_locales": "Sin registros locales",
        "lbl_todos_trabajos": "Todos los trabajos",
        "lbl_todos_los_anos": "Todos los años",
        "tipo_vacaciones": "Vacaciones",
        "tipo_puente": "Puente",
        "tipo_dia_libre": "Día Libre",
        "tipo_festivo_manual": "Festivo (Manual)",
        "estado_ok": "OK",
        "estado_pendiente": "PENDIENTE",
        "estado_futuro": "Futuro",
        "estado_listo_subir": "LISTO (Subir)",
        "estado_pendiente_subir": "PENDIENTE (Subir)",
        "notif_titulo": "⚠️ Mantenimiento Preventivo",
        "notif_cuerpo": "Tienes trabajos recurrentes pendientes de realizar.",
        "mes_01": "Enero", "mes_02": "Febrero", "mes_03": "Marzo", "mes_04": "Abril", "mes_05": "Mayo", "mes_06": "Junio", "mes_07": "Julio", "mes_08": "Agosto", "mes_09": "Septiembre", "mes_10": "Octubre", "mes_11": "Noviembre", "mes_12": "Diciembre",
        "mes_todo": "Todo el año", "mes_01_corto": "Ene", "mes_02_corto": "Feb", "mes_03_corto": "Mar", "mes_04_corto": "Abr", "mes_05_corto": "May", "mes_06_corto": "Jun", "mes_07_corto": "Jul", "mes_08_corto": "Ago", "mes_09_corto": "Sep", "mes_10_corto": "Oct", "mes_11_corto": "Nov", "mes_12_corto": "Dic",

        # --- Menú Archivo ---
        "menu_archivo": "&Archivo",
        "menu_backup": "💾 Backup",
        "menu_restaurar": "♻️ Restaurar",
        "menu_opciones_pdf": "📄 Opciones PDF",
        "menu_generar_pdf": "📄 Generar PDF Ahora",
        "menu_add_logo": "🖼️ Añadir / Cambiar Logo",
        "menu_quitar_logo": "❌ Quitar Logo",
        "menu_csv": "📄 CSV",
        "menu_excel": "📊 Excel",
        "menu_salir": "Salir",

        # --- Menú Herramientas ---
        "menu_herramientas": "&Herramientas",
        "menu_sync_qr": "📲 Sincronizar App (QR)",
        "menu_gestionar_dias": "Gestionar Días / Festivos",
        "menu_pais_region": "🌍 País / Región (Festivos)",
        "menu_idioma": "🌐 Idioma",
        "menu_limpiar_fotos": "🧹 Limpiar Fotos Basura",

        # --- Menú Ayuda ---
        "menu_ayuda": "&Ayuda",
        "menu_buscar_actualizaciones": "🔄 Buscar Actualizaciones",
        "menu_acerca_de": "ℹ️ Acerca de",

        # --- Pestañas ---
        "tab_dashboard": "📊 Dashboard",
        "tab_calendario": "📅 Calendario",
        "tab_avisos": "⚠️ Avisos",
        "tab_registrar": "📝 Registrar",
        "tab_historial": "🗂 Historial",
        "tab_buscador": "🔍 Buscador",
        "tab_pendientes": "🔨 Pendientes",

        # --- Diálogo de idioma / reinicio ---
        "dlg_idioma_titulo": "Cambiar Idioma",
        "dlg_idioma_reinicio_texto": "El idioma se aplicará la próxima vez que abras la aplicación.\n¿Cerrar la aplicación ahora?",

        # --- Botones genéricos ---
        "btn_cerrar": "Cerrar",
        "btn_cancelar": "Cancelar",
        "btn_anadir": "Añadir",
        "btn_borrar_seleccionado": "🗑️ Borrar Seleccionado",
        "btn_editar": "✏️ Editar",
        "btn_editar_seleccionado": "✏️ Editar Seleccionado",
        "btn_eliminar": "❌ Eliminar",
        "btn_completar": "✅ Completar",
        "btn_elegir_foto": "✅ ELEGIR ESTA FOTO",
        "btn_cambiar_foto": "📂 Cambiar",
        "btn_borrar_foto": "❌ Borrar",
        "btn_ver_grande": "🔍 Ver Grande",
        "btn_buscar_foto_manual": "📸 Buscar Foto Manualmente",
        "btn_quitar_foto": "❌ Quitar Foto",
        "btn_quitar_foto_despues": "❌ Quitar Foto Después",
        "btn_sincronizar_app": "📲 Sincronizar App",
        "btn_guardar_registro": "💾 GUARDAR REGISTRO",
        "btn_ir_hoy": "Ir a Hoy",
        "btn_gestion_dias": "Gestión Días",
        "btn_anadir_aviso": "Añadir Aviso",
        "btn_guardar_form": "Guardar",

        # --- Etiquetas de formularios ---
        "lbl_seleccionar_archivo": "Selecciona un archivo...",
        "lbl_qr_paso1": "1. Abre la App 'MantPro' en el móvil",
        "lbl_qr_paso2": "2. Dale al botón de escanear",
        "lbl_fecha": "Fecha:",
        "lbl_tipo": "Tipo:",
        "lbl_elige_pais": "Elige tu país para descargar los días festivos:",
        "lbl_nota_espana": "(Para España se podrá afinar después por provincia)",
        "lbl_elige_provincia": "Elige tu provincia para descargar los días festivos:",
        "lbl_nota_provincia": "(Se descargarán festivos nacionales + comunidad + provincia)",
        "lbl_descripcion": "Descripción:",
        "lbl_fotos_antes_despues": "📸 Fotos (ANTES y DESPUÉS):",
        "lbl_antes": "ANTES:",
        "lbl_despues": "DESPUÉS:",
        "lbl_etiquetas": "Etiquetas:",
        "lbl_etiquetas_rapidas": "Etiquetas Rápidas:",
        "lbl_titulo": "Título:",
        "lbl_detalles": "Detalles:",
        "lbl_foto_adjunta": "📸 Foto Adjunta:",
        "lbl_sin_foto": "Sin foto",
        "lbl_fecha_finalizacion": "Fecha Finalización:",
        "lbl_otros_tags": "Otros Tags (Opcional):",
        "ph_ejemplo_tags": "Ej: limpieza, rodamiento...",
        "lbl_titulo_aviso": "Título del Aviso:",
        "lbl_fecha_inicio": "Fecha de Inicio:",
        "lbl_frecuencia_repeticion": "Frecuencia de Repetición:",
        "lbl_dias_margen": "Días que permanece activo (margen):",
        "lbl_de": "De:",
        "lbl_a": "A:",
        "lbl_resumen_tarea": "Resumen / Tarea:",
        "ph_resumen": "Resumen corto del trabajo...",
        "lbl_gestion_avisos": "⚠️ GESTIÓN DE AVISOS RECURRENTES",
        "lbl_inicio": "Inicio:",
        "lbl_repetir": "Repetir:",
        "lbl_duracion": "Duración:",
        "lbl_lista_pendientes": "LISTA DE PENDIENTES",
        "lbl_ultimas_intervenciones": "📋 Últimas Intervenciones",
        "lbl_distribucion": "📊 Distribución",
        "lbl_procesando_pdf": "Procesando imágenes y generando documento...\nPor favor espera.",
        "freq_anual": "Anual", "freq_semestral": "Semestral", "freq_trimestral": "Trimestral",
        "freq_mensual": "Mensual", "freq_semanal": "Semanal", "freq_diario": "Diario",

        # --- Diálogos: títulos ---
        "title_error": "Error",
        "title_actualizado": "Actualizado",
        "title_nueva_version": "🚀 Nueva versión disponible",
        "title_region_cambiada": "Región Cambiada",
        "title_pais_cambiado": "País Cambiado",
        "title_atencion": "Atención",
        "title_backup_completo": "Backup Completo",
        "title_error_backup": "Error Backup",
        "title_restaurar_copia": "Restaurar Copia",
        "title_seleccionar_backup": "Seleccionar Backup Completo",
        "title_restauracion": "Restauración",
        "title_error_restauracion": "Error Restauración",
        "title_exportar_csv": "Exportar a CSV",
        "title_exportado": "Exportado",
        "title_falta_libreria": "Falta librería",
        "title_logo_actualizado": "Logo Actualizado",
        "title_logo_borrado": "Logo Borrado",
        "title_informacion": "Información",
        "title_error_db": "Error DB",
        "title_exito": "Éxito",
        "title_error_pdf": "Error PDF",
        "title_limpieza": "Limpieza",
        "title_acerca_de": "Acerca de MantPro",
        "title_borrar_aviso": "Borrar Aviso",
        "title_confirmar_eliminacion": "Confirmar Eliminación",
        "title_confirmar_borrado": "Confirmar Borrado",
        "title_error_fatal": "Error Fatal 💥",
        "title_seleccionar_carpeta_pdf": "Seleccionar Carpeta para Guardar los PDFs",

        # --- Diálogos: mensajes ---
        "msg_error_conexion_github": "No se pudo conectar con GitHub para buscar actualizaciones.",
        "msg_ya_actualizado": "✅ Ya tienes la última versión instalada (v{v}).",
        "msg_nueva_version_disponible": "Tienes la versión {actual} instalada y en GitHub ya está la {nueva}.",
        "msg_quieres_descargar": "¿Quieres descargarla ahora?",
        "btn_descargar": "Descargar",
        "btn_luego": "Luego",
        "msg_region_cambiada": "País: España\nNueva zona: {zona}\n(Se descargarán festivos nacionales, de {parent} y de {prov})",
        "msg_pais_cambiado": "Nuevo país: {pais}\n(Se descargarán los festivos nacionales de {pais})",
        "msg_falta_resumen": "Falta el resumen",
        "msg_backup_guardado": "Copia limpia y guardada:\n{archivo}",
        "msg_advertencia_restaurar": "⚠️ ATENCIÓN ⚠️\n\nAl restaurar, se SOBRESCRIBIRÁN todos los datos.\n¿Continuar?",
        "msg_sistema_restaurado": "✅ Sistema restaurado correctamente.",
        "msg_zip_corrupto": "ZIP corrupto:\n{error}",
        "msg_csv_guardado": "CSV guardado correctamente.",
        "msg_instalar_xlsxwriter": "Instala: pip install xlsxwriter",
        "msg_excel_guardado": "Excel guardado correctamente.",
        "msg_logo_actualizado": "✅ Logo actualizado. Aparecerá en el próximo PDF.",
        "msg_logo_borrado": "🗑️ El logo ha sido eliminado del sistema.",
        "msg_sin_logo": "No había ningún logo configurado.",
        "msg_fotos_basura": "Hay {n} fotos basura. ¿Borrar?",
        "msg_confirmar_borrar_aviso": "¿Estás seguro de borrar este aviso recurrente definitivamente?",
        "btn_si": "SÍ",
        "btn_no": "NO",
        "msg_confirmar_eliminacion_registro": "¿Borrar registro permanentemente?\nSi tiene foto adjunta, se eliminará del disco.\n\nSi es un preventivo reciente, volverá a marcarse como PENDIENTE.",
        "msg_confirmar_borrar_pendiente": "¿Estás seguro de borrar este trabajo pendiente?",
        "msg_error_fatal": "El programa ha fallado. Dale a 'Show Details' para ver por qué:",

        # --- Títulos de ventana (diálogos que no son QMessageBox) ---
        "title_visor_imagen": "Visor de Imagen",
        "title_visor_manual": "📸 VISOR MANUAL",
        "title_sincronizar_movil": "Sincronizar Móvil",
        "title_gestion_dias_especiales": "Gestión de Días Especiales",
        "title_seleccionar_pais": "Seleccionar País",
        "title_seleccionar_provincia": "Seleccionar Provincia",
        "title_editar_registro": "Editar Registro",
        "title_editar_tarea_pendiente": "Editar Tarea Pendiente",
        "title_editar_aviso": "✏️ Editar Aviso Recurrente",
        "title_exportar_pdf": "Exportar a PDF",
        "title_control_mantenimiento": "Control Mantenimiento",
        "title_generando_pdf": "Generando PDF...",
        "tag_urgente": "Urgente",
        "tag_electrico": "Eléctrico",
        "tag_mecanico": "Mecánico",
        "tag_preventivo": "Preventivo",

        # --- Dashboard y Tablas PC ---
        "lbl_avisos_pendientes": "Avisos Pendientes",
        "lbl_tareas_por_hacer": "Tareas Por Hacer",
        "lbl_registros_este_mes": "Registros este Mes",
        "hdr_estado": "Estado",
        "hdr_titulo": "Título",
        "hdr_frecuencia": "Frecuencia",
        "hdr_proxima": "Próxima",
        "hdr_sit": "Sit",

        # --- Formularios y Placeholders ---
        "lbl_opciones_exportacion": "Opciones de Exportación",
        "lbl_exportar_todo": "Exportar TODO el historial",
        "lbl_exportar_rango": "Exportar rango de fechas",
        "lbl_exportar_por_mes": "Exportar un PDF por mes",
        "lbl_incluir_imagenes": "📸 Incluir imágenes en el PDF",
        "lbl_crear_nuevo_aviso": "Crear Nuevo Aviso",
        "ph_titulo_aviso": "Título del aviso...",
        "ph_buscar_texto": "🔍 Buscar texto (Motor, Fuga, KM1)...",
        "lbl_nuevo_trabajo": "Nuevo Trabajo",
        "ph_titulo": "Título",
        "ph_detalles": "Detalles",
        "lbl_acciones": "Acciones",
        "ph_otros_tags": "Otros Tags (Opcional):",
        "ph_otras_etiquetas": "Otras etiquetas (separadas por comas)...",

        # --- Mensajes y Snackbars ---
        "msg_registro_guardado": "✅ Registro guardado correctamente",
        "msg_tarea_completada": "✅ Tarea '{titulo}' completada",
        "msg_guardado_historial": "✅ Guardado en historial: {titulo}",
        "msg_eliminado_historial": "🗑️ Eliminado del historial: {titulo}",
        "msg_pendiente_actualizado": "✅ Pendiente actualizado",
        "msg_mostrando_resultados": "🔍 Mostrando {n} resultados",

        "lbl_arrastra_foto": "Arrastra una foto aquí\no haz clic para buscar",
        "lbl_formato_invalido": "Formato no válido",
        "lbl_arrastra_despues": "Arrastra foto DESPUÉS aquí",
        "lbl_arrastra_click": "Arrastra o click",

        # --- Micro-textos finales ---
        "msg_error_cargar_imagen": "Error al cargar la imagen",
        "msg_es_carpeta": "📁 Es una carpeta",
        "msg_no_imagen_valida": "❌ No es una imagen válida",
        "title_seleccionar_logo": "Seleccionar Logo",
        "title_guardar_pdf": "Guardar PDF",
        "title_exportar_excel": "Exportar a Excel",
        "lbl_info": "Info",
        "btn_aceptar": "Aceptar",

        # --- Usuarios, login y autoría de trabajos ---
        "hdr_realizado_por": "REALIZADO POR",
        "menu_usuarios": "👥 Gestión de usuarios",
        "menu_cambiar_password": "🔑 Cambiar mi contraseña",
        "msg_solo_admin": "Solo un administrador puede gestionar usuarios.",
        "login_titulo": "MantPro — Acceso",
        "login_usuario": "Usuario",
        "login_password": "Contraseña",
        "login_entrar": "Entrar",
        "login_vacio": "Introduce usuario y contraseña.",
        "login_error": "Usuario o contraseña incorrectos.",
        "login_cambio_requerido": "Debes cambiar la contraseña para entrar.",
        "salir": "Salir",
        "cerrar": "Cerrar",
        "aviso": "Aviso",
        "ok": "Hecho",
        "password_titulo": "Cambiar contraseña",
        "password_obligatorio": "Es tu primer acceso: define una contraseña nueva.",
        "password_actual": "Contraseña actual",
        "password_nueva": "Contraseña nueva",
        "password_repetir": "Repetir",
        "password_no_coincide": "Las contraseñas no coinciden.",
        "usuarios_titulo": "Gestión de usuarios",
        "usuarios_col_login": "Usuario",
        "usuarios_col_nombre": "Nombre",
        "usuarios_col_rol": "Rol",
        "usuarios_col_estado": "Estado",
        "usuarios_col_acceso": "Último acceso",
        "rol_admin": "Administrador",
        "rol_tecnico": "Técnico",
        "activo": "Activo",
        "inactivo": "Inactivo",
        "usuarios_forzar_cambio": "Pedir cambio al entrar",
        "usuarios_anadir": "➕ Añadir",
        "usuarios_reset": "🔑 Restablecer contraseña",
        "usuarios_cambiar_rol": "🎚 Cambiar rol",
        "usuarios_activar": "🚫 Activar / Desactivar",
        "usuarios_selecciona": "Selecciona un usuario de la lista.",
        "filtro_todos": "Todos",
        "lbl_sin_asignar": "Sin asignar",
        "lbl_ver_de": "Ver los de",
        "lbl_asignar_a": "Asignar a",
        "btn_reasignar": "👤 Reasignar",
    },
    "en": {
        # --- Listas, Estados y Notificaciones ---
        "hdr_fecha": "DATE",
        "hdr_descripcion": "DESCRIPTION",
        "hdr_tags": "TAGS",
        "hdr_foto_antes": "BEFORE PHOTO",
        "hdr_foto_despues": "AFTER PHOTO",
        "msg_dia_no_laborable": "--- Non-working day ---",
        "msg_nada_registrado": "--- Nothing recorded ---",
        "msg_nada": "--- Nothing ---",
        "msg_sin_detalles": "No details",
        "msg_no_hay_pendientes": "No pending tasks",
        "msg_no_hay_avisos": "No alerts",
        "msg_sin_historial": "No history visible",
        "msg_sin_registros_locales": "No local records",
        "lbl_todos_trabajos": "All jobs",
        "lbl_todos_los_anos": "All years",
        "tipo_vacaciones": "Vacation",
        "tipo_puente": "Long Weekend",
        "tipo_dia_libre": "Day Off",
        "tipo_festivo_manual": "Holiday (Manual)",
        "estado_ok": "OK",
        "estado_pendiente": "PENDING",
        "estado_futuro": "Future",
        "estado_listo_subir": "READY (Upload)",
        "estado_pendiente_subir": "PENDING (Upload)",
        "notif_titulo": "⚠️ Preventive Maintenance",
        "notif_cuerpo": "You have pending recurring jobs to do.",
        "mes_01": "January", "mes_02": "February", "mes_03": "March", "mes_04": "April", "mes_05": "May", "mes_06": "June", "mes_07": "July", "mes_08": "August", "mes_09": "September", "mes_10": "October", "mes_11": "November", "mes_12": "December",
        "mes_todo": "All year", "mes_01_corto": "Jan", "mes_02_corto": "Feb", "mes_03_corto": "Mar", "mes_04_corto": "Apr", "mes_05_corto": "May", "mes_06_corto": "Jun", "mes_07_corto": "Jul", "mes_08_corto": "Aug", "mes_09_corto": "Sep", "mes_10_corto": "Oct", "mes_11_corto": "Nov", "mes_12_corto": "Dec",

        # --- File menu ---
        "menu_archivo": "&File",
        "menu_backup": "💾 Backup",
        "menu_restaurar": "♻️ Restore",
        "menu_opciones_pdf": "📄 PDF Options",
        "menu_generar_pdf": "📄 Generate PDF Now",
        "menu_add_logo": "🖼️ Add / Change Logo",
        "menu_quitar_logo": "❌ Remove Logo",
        "menu_csv": "📄 CSV",
        "menu_excel": "📊 Excel",
        "menu_salir": "Exit",

        # --- Tools menu ---
        "menu_herramientas": "&Tools",
        "menu_sync_qr": "📲 Sync App (QR)",
        "menu_gestionar_dias": "Manage Days / Holidays",
        "menu_pais_region": "🌍 Country / Region (Holidays)",
        "menu_idioma": "🌐 Language",
        "menu_limpiar_fotos": "🧹 Clean Orphan Photos",

        # --- Help menu ---
        "menu_ayuda": "&Help",
        "menu_buscar_actualizaciones": "🔄 Check for Updates",
        "menu_acerca_de": "ℹ️ About",

        # --- Tabs ---
        "tab_dashboard": "📊 Dashboard",
        "tab_calendario": "📅 Calendar",
        "tab_avisos": "⚠️ Alerts",
        "tab_registrar": "📝 New Entry",
        "tab_historial": "🗂 History",
        "tab_buscador": "🔍 Search",
        "tab_pendientes": "🔨 Pending",

        # --- Language dialog / restart ---
        "dlg_idioma_titulo": "Change Language",
        "dlg_idioma_reinicio_texto": "The language will be applied next time you open the app.\nClose the app now?",

        # --- Generic buttons ---
        "btn_cerrar": "Close",
        "btn_cancelar": "Cancel",
        "btn_anadir": "Add",
        "btn_borrar_seleccionado": "🗑️ Delete Selected",
        "btn_editar": "✏️ Edit",
        "btn_editar_seleccionado": "✏️ Edit Selected",
        "btn_eliminar": "❌ Delete",
        "btn_completar": "✅ Complete",
        "btn_elegir_foto": "✅ CHOOSE THIS PHOTO",
        "btn_cambiar_foto": "📂 Change",
        "btn_borrar_foto": "❌ Delete",
        "btn_ver_grande": "🔍 View Full Size",
        "btn_buscar_foto_manual": "📸 Browse for Photo Manually",
        "btn_quitar_foto": "❌ Remove Photo",
        "btn_quitar_foto_despues": "❌ Remove After Photo",
        "btn_sincronizar_app": "📲 Sync App",
        "btn_guardar_registro": "💾 SAVE RECORD",
        "btn_ir_hoy": "Go to Today",
        "btn_gestion_dias": "Manage Days",
        "btn_anadir_aviso": "Add Alert",
        "btn_guardar_form": "Save",

        # --- Form labels ---
        "lbl_seleccionar_archivo": "Select a file...",
        "lbl_qr_paso1": "1. Open the 'MantPro' App on your phone",
        "lbl_qr_paso2": "2. Tap the scan button",
        "lbl_fecha": "Date:",
        "lbl_tipo": "Type:",
        "lbl_elige_pais": "Choose your country to download public holidays:",
        "lbl_nota_espana": "(For Spain you can refine this further by province next)",
        "lbl_elige_provincia": "Choose your province to download public holidays:",
        "lbl_nota_provincia": "(National + regional + provincial holidays will be downloaded)",
        "lbl_descripcion": "Description:",
        "lbl_fotos_antes_despues": "📸 Photos (BEFORE and AFTER):",
        "lbl_antes": "BEFORE:",
        "lbl_despues": "AFTER:",
        "lbl_etiquetas": "Tags:",
        "lbl_etiquetas_rapidas": "Quick Tags:",
        "lbl_titulo": "Title:",
        "lbl_detalles": "Details:",
        "lbl_foto_adjunta": "📸 Attached Photo:",
        "lbl_sin_foto": "No photo",
        "lbl_fecha_finalizacion": "Due Date:",
        "lbl_otros_tags": "Other Tags (Optional):",
        "ph_ejemplo_tags": "E.g.: cleaning, bearing...",
        "lbl_titulo_aviso": "Alert Title:",
        "lbl_fecha_inicio": "Start Date:",
        "lbl_frecuencia_repeticion": "Repeat Frequency:",
        "lbl_dias_margen": "Days it stays active (margin):",
        "lbl_de": "From:",
        "lbl_a": "To:",
        "lbl_resumen_tarea": "Summary / Task:",
        "ph_resumen": "Short summary of the job...",
        "lbl_gestion_avisos": "⚠️ MANAGE RECURRING ALERTS",
        "lbl_inicio": "Start:",
        "lbl_repetir": "Repeat:",
        "lbl_duracion": "Duration:",
        "lbl_lista_pendientes": "PENDING LIST",
        "lbl_ultimas_intervenciones": "📋 Latest Interventions",
        "lbl_distribucion": "📊 Breakdown",
        "lbl_procesando_pdf": "Processing images and generating document...\nPlease wait.",
        "freq_anual": "Yearly", "freq_semestral": "Half-yearly", "freq_trimestral": "Quarterly",
        "freq_mensual": "Monthly", "freq_semanal": "Weekly", "freq_diario": "Daily",

        # --- Dialog messages: titles ---
        "title_error": "Error",
        "title_actualizado": "Up to Date",
        "title_nueva_version": "🚀 New Version Available",
        "title_region_cambiada": "Region Changed",
        "title_pais_cambiado": "Country Changed",
        "title_atencion": "Attention",
        "title_backup_completo": "Backup Complete",
        "title_error_backup": "Backup Error",
        "title_restaurar_copia": "Restore Backup",
        "title_seleccionar_backup": "Select Full Backup",
        "title_restauracion": "Restore",
        "title_error_restauracion": "Restore Error",
        "title_exportar_csv": "Export to CSV",
        "title_exportado": "Exported",
        "title_falta_libreria": "Missing Library",
        "title_logo_actualizado": "Logo Updated",
        "title_logo_borrado": "Logo Removed",
        "title_informacion": "Information",
        "title_error_db": "DB Error",
        "title_exito": "Success",
        "title_error_pdf": "PDF Error",
        "title_limpieza": "Cleanup",
        "title_acerca_de": "About MantPro",
        "title_borrar_aviso": "Delete Alert",
        "title_confirmar_eliminacion": "Confirm Deletion",
        "title_confirmar_borrado": "Confirm Deletion",
        "title_error_fatal": "Fatal Error 💥",
        "title_seleccionar_carpeta_pdf": "Select Folder to Save PDFs",

        # --- Dialog messages: bodies ---
        "msg_error_conexion_github": "Could not connect to GitHub to check for updates.",
        "msg_ya_actualizado": "✅ You already have the latest version installed (v{v}).",
        "msg_nueva_version_disponible": "You have version {actual} installed and GitHub already has version {nueva}.",
        "msg_quieres_descargar": "Do you want to download it now?",
        "btn_descargar": "Download",
        "btn_luego": "Later",
        "msg_region_cambiada": "Country: Spain\nNew region: {zona}\n(National, {parent} and {prov} holidays will be downloaded)",
        "msg_pais_cambiado": "New country: {pais}\n(National holidays for {pais} will be downloaded)",
        "msg_falta_resumen": "Summary is missing",
        "msg_backup_guardado": "Backup saved cleanly:\n{archivo}",
        "msg_advertencia_restaurar": "⚠️ WARNING ⚠️\n\nRestoring will OVERWRITE all current data.\nContinue?",
        "msg_sistema_restaurado": "✅ System restored successfully.",
        "msg_zip_corrupto": "Corrupt ZIP file:\n{error}",
        "msg_csv_guardado": "CSV saved successfully.",
        "msg_instalar_xlsxwriter": "Install it with: pip install xlsxwriter",
        "msg_excel_guardado": "Excel saved successfully.",
        "msg_logo_actualizado": "✅ Logo updated. It will appear on the next PDF.",
        "msg_logo_borrado": "🗑️ The logo has been removed from the system.",
        "msg_sin_logo": "There was no logo configured.",
        "msg_fotos_basura": "There are {n} orphan photos. Delete them?",
        "msg_confirmar_borrar_aviso": "Are you sure you want to permanently delete this recurring alert?",
        "btn_si": "YES",
        "btn_no": "NO",
        "msg_confirmar_eliminacion_registro": "Delete this record permanently?\nIf it has an attached photo, it will be removed from disk.\n\nIf it's a recent preventive task, it will be marked as PENDING again.",
        "msg_confirmar_borrar_pendiente": "Are you sure you want to delete this pending job?",
        "msg_error_fatal": "The program has crashed. Click 'Show Details' to see why:",

        # --- Window titles (non-QMessageBox dialogs) ---
        "title_visor_imagen": "Image Viewer",
        "title_visor_manual": "📸 MANUAL VIEWER",
        "title_sincronizar_movil": "Sync Mobile",
        "title_gestion_dias_especiales": "Manage Special Days",
        "title_seleccionar_pais": "Select Country",
        "title_seleccionar_provincia": "Select Province",
        "title_editar_registro": "Edit Record",
        "title_editar_tarea_pendiente": "Edit Pending Task",
        "title_editar_aviso": "✏️ Edit Recurring Alert",
        "title_exportar_pdf": "Export to PDF",
        "title_control_mantenimiento": "Maintenance Control",
        "title_generando_pdf": "Generating PDF...",
        "tag_urgente": "Urgent",
        "tag_electrico": "Electrical",
        "tag_mecanico": "Mechanical",
        "tag_preventivo": "Preventive",

        # --- Dashboard y Tablas PC ---
        "lbl_avisos_pendientes": "Pending Alerts",
        "lbl_tareas_por_hacer": "To-Do Tasks",
        "lbl_registros_este_mes": "Records this Month",
        "hdr_estado": "Status",
        "hdr_titulo": "Title",
        "hdr_frecuencia": "Frequency",
        "hdr_proxima": "Next",
        "hdr_sit": "Status",

        # --- Formularios y Placeholders ---
        "lbl_opciones_exportacion": "Export Options",
        "lbl_exportar_todo": "Export ALL history",
        "lbl_exportar_rango": "Export date range",
        "lbl_exportar_por_mes": "Export one PDF per month",
        "lbl_incluir_imagenes": "📸 Include images in PDF",
        "lbl_crear_nuevo_aviso": "Create New Alert",
        "ph_titulo_aviso": "Alert title...",
        "ph_buscar_texto": "🔍 Search text (Motor, Leak, KM1)...",
        "lbl_nuevo_trabajo": "New Job",
        "ph_titulo": "Title",
        "ph_detalles": "Details",
        "lbl_acciones": "Actions",
        "ph_otros_tags": "Other tags...",
        "ph_otras_etiquetas": "Other tags (comma separated)...",

        # --- Mensajes y Snackbars ---
        "msg_registro_guardado": "✅ Record saved successfully",
        "msg_tarea_completada": "✅ Task '{titulo}' completed",
        "msg_guardado_historial": "✅ Saved in history: {titulo}",
        "msg_eliminado_historial": "🗑️ Removed from history: {titulo}",
        "msg_pendiente_actualizado": "✅ Pending task updated",
        "msg_mostrando_resultados": "🔍 Showing {n} results",

        "lbl_arrastra_foto": "Drag a photo here\nor click to browse",
        "lbl_formato_invalido": "Invalid format",
        "lbl_arrastra_despues": "Drag AFTER photo here",
        "lbl_arrastra_click": "Drag or click",

        # --- Micro-textos finales ---
        "msg_error_cargar_imagen": "Error al cargar la imagen",
        "msg_es_carpeta": "📁 Es una carpeta",
        "msg_no_imagen_valida": "❌ No es una imagen válida",
        "title_seleccionar_logo": "Seleccionar Logo",
        "title_guardar_pdf": "Guardar PDF",
        "title_exportar_excel": "Exportar a Excel",
        "lbl_info": "Info",
        "btn_aceptar": "Accept",

        # --- Usuarios, login y autoría de trabajos ---
        "hdr_realizado_por": "PERFORMED BY",
        "menu_usuarios": "👥 User management",
        "menu_cambiar_password": "🔑 Change my password",
        "msg_solo_admin": "Only an administrator can manage users.",
        "login_titulo": "MantPro — Sign in",
        "login_usuario": "User",
        "login_password": "Password",
        "login_entrar": "Sign in",
        "login_vacio": "Enter your user and password.",
        "login_error": "Wrong user or password.",
        "login_cambio_requerido": "You must change your password to sign in.",
        "salir": "Exit",
        "cerrar": "Close",
        "aviso": "Notice",
        "ok": "Done",
        "password_titulo": "Change password",
        "password_obligatorio": "This is your first sign-in: set a new password.",
        "password_actual": "Current password",
        "password_nueva": "New password",
        "password_repetir": "Repeat",
        "password_no_coincide": "The passwords do not match.",
        "usuarios_titulo": "User management",
        "usuarios_col_login": "User",
        "usuarios_col_nombre": "Name",
        "usuarios_col_rol": "Role",
        "usuarios_col_estado": "Status",
        "usuarios_col_acceso": "Last sign-in",
        "rol_admin": "Administrator",
        "rol_tecnico": "Technician",
        "activo": "Active",
        "inactivo": "Inactive",
        "usuarios_forzar_cambio": "Require change at sign-in",
        "usuarios_anadir": "➕ Add",
        "usuarios_reset": "🔑 Reset password",
        "usuarios_cambiar_rol": "🎚 Change role",
        "usuarios_activar": "🚫 Enable / Disable",
        "usuarios_selecciona": "Select a user from the list.",
        "filtro_todos": "All",
        "lbl_sin_asignar": "Unassigned",
        "lbl_ver_de": "Show those of",
        "lbl_asignar_a": "Assign to",
        "btn_reasignar": "👤 Reassign",
    },
    "eu": {
        "hdr_fecha": "DATA",
        "hdr_descripcion": "DESKRIBAPENA",
        "hdr_tags": "ETIKETAK",
        "hdr_foto_antes": "AURREKO ARGAZKIA",
        "hdr_foto_despues": "ONDORENGO ARGAZKIA",
        "msg_dia_no_laborable": "--- Lan-eguna ez ---",
        "msg_nada_registrado": "--- Ezer ez erregistratuta ---",
        "msg_nada": "--- Ezer ez ---",
        "msg_sin_detalles": "Xehetasunik ez",
        "msg_no_hay_pendientes": "Ez dago zereginik",
        "msg_no_hay_avisos": "Ez dago abisurik",
        "msg_sin_historial": "Ez dago historiarik",
        "msg_sin_registros_locales": "Erregistro lokalik ez",
        "lbl_todos_trabajos": "Lan guztiak",
        "lbl_todos_los_anos": "Urte guztiak",
        "tipo_vacaciones": "Oporrak",
        "tipo_puente": "Zubia",
        "tipo_dia_libre": "Jai eguna",
        "tipo_festivo_manual": "Jaieguna (Eskuzkoa)",
        "estado_ok": "OK",
        "estado_pendiente": "ZAIN",
        "estado_futuro": "Etorkizuna",
        "estado_listo_subir": "PREST (Igo)",
        "estado_pendiente_subir": "ZAIN (Igo)",
        "notif_titulo": "⚠️ Prebentziozko Mantentzea",
        "notif_cuerpo": "Errepikatzen diren lanak dituzu egiteko.",
        "mes_01": "Urtarrila", "mes_02": "Otsaila", "mes_03": "Martxoa", "mes_04": "Apirila", "mes_05": "Maiatza", "mes_06": "Ekaina", "mes_07": "Uztaila", "mes_08": "Abuztua", "mes_09": "Iraila", "mes_10": "Urria", "mes_11": "Azaroa", "mes_12": "Abendua",
        "mes_todo": "Urte osoa", "mes_01_corto": "Urt", "mes_02_corto": "Ots", "mes_03_corto": "Mar", "mes_04_corto": "Api", "mes_05_corto": "Mai", "mes_06_corto": "Eka", "mes_07_corto": "Uzt", "mes_08_corto": "Abu", "mes_09_corto": "Ira", "mes_10_corto": "Urr", "mes_11_corto": "Aza", "mes_12_corto": "Abe",
        "menu_archivo": "&Fitxategia",
        "menu_backup": "💾 Babeskopia",
        "menu_restaurar": "♻️ Berrezarri",
        "menu_opciones_pdf": "📄 PDF Aukerak",
        "menu_generar_pdf": "📄 Sortu PDFa orain",
        "menu_add_logo": "🖼️ Gehitu / Aldatu Logoa",
        "menu_quitar_logo": "❌ Kendu Logoa",
        "menu_csv": "📄 CSV",
        "menu_excel": "📊 Excel",
        "menu_salir": "Irten",
        "menu_herramientas": "&Tresnak",
        "menu_sync_qr": "📲 Sinkronizatu Appa (QR)",
        "menu_gestionar_dias": "Kudeatu Egunak / Jaiegunak",
        "menu_pais_region": "🌍 Herrialdea / Eskualdea (Jaiegunak)",
        "menu_idioma": "🌐 Hizkuntza",
        "menu_limpiar_fotos": "🧹 Garbitu Zabor-argazkiak",
        "menu_ayuda": "&Laguntza",
        "menu_buscar_actualizaciones": "🔄 Bilatu Eguneraketak",
        "menu_acerca_de": "ℹ️ Honi buruz",
        "tab_dashboard": "📊 Aginte-mahaia",
        "tab_calendario": "📅 Egutegia",
        "tab_avisos": "⚠️ Abisuak",
        "tab_registrar": "📝 Erregistratu",
        "tab_historial": "🗂 Historia",
        "tab_buscador": "🔍 Bilatzailea",
        "tab_pendientes": "🔨 Egiteke",
        "dlg_idioma_titulo": "Aldatu Hizkuntza",
        "dlg_idioma_reinicio_texto": "Hizkuntza aplikazioa hurrengo aldiz irekitzean aplikatuko da.\nItxi aplikazioa orain?",
        "btn_cerrar": "Itxi",
        "btn_cancelar": "Utzi",
        "btn_anadir": "Gehitu",
        "btn_borrar_seleccionado": "🗑️ Ezabatu Hautatua",
        "btn_editar": "✏️ Editatu",
        "btn_editar_seleccionado": "✏️ Editatu Hautatua",
        "btn_eliminar": "❌ Ezabatu",
        "btn_completar": "✅ Osatu",
        "btn_elegir_foto": "✅ AUKERATU ARGAZKI HAU",
        "btn_cambiar_foto": "📂 Aldatu",
        "btn_borrar_foto": "❌ Ezabatu",
        "btn_ver_grande": "🔍 Ikusi Handia",
        "btn_buscar_foto_manual": "📸 Bilatu Argazkia Eskuz",
        "btn_quitar_foto": "❌ Kendu Argazkia",
        "btn_quitar_foto_despues": "❌ Kendu Ondorengo Argazkia",
        "btn_sincronizar_app": "📲 Sinkronizatu Appa",
        "btn_guardar_registro": "💾 GORDE ERREGISTROA",
        "btn_ir_hoy": "Joan Gaurkora",
        "btn_gestion_dias": "Egunen Kudeaketa",
        "btn_anadir_aviso": "Gehitu Abisua",
        "btn_guardar_form": "Gorde",
        "lbl_seleccionar_archivo": "Hautatu fitxategi bat...",
        "lbl_qr_paso1": "1. Ireki 'MantPro' Appa mugikorrean",
        "lbl_qr_paso2": "2. Sakatu eskaneatu botoia",
        "lbl_fecha": "Data:",
        "lbl_tipo": "Mota:",
        "lbl_elige_pais": "Aukeratu zure herrialdea jaiegunak deskargatzeko:",
        "lbl_nota_espana": "(Espainiarako probintziaren arabera zehaztu ahal izango da)",
        "lbl_elige_provincia": "Aukeratu zure probintzia jaiegunak deskargatzeko:",
        "lbl_nota_provincia": "(Jaiegun nazionalak + erkidegokoak + probintziakoak deskargatuko dira)",
        "lbl_descripcion": "Deskribapena:",
        "lbl_fotos_antes_despues": "📸 Argazkiak (AURREKOA eta ONDORENGOA):",
        "lbl_antes": "AURREKOA:",
        "lbl_despues": "ONDORENGOA:",
        "lbl_etiquetas": "Etiketak:",
        "lbl_etiquetas_rapidas": "Etiketa Lasterrak:",
        "lbl_titulo": "Izenburua:",
        "lbl_detalles": "Xehetasunak:",
        "lbl_foto_adjunta": "📸 Erantsitako Argazkia:",
        "lbl_sin_foto": "Argazkirik ez",
        "lbl_fecha_finalizacion": "Amaiera Data:",
        "lbl_otros_tags": "Beste Etiketa batzuk (Aukerakoa):",
        "ph_ejemplo_tags": "Adibidez: garbiketa, errodamendua...",
        "lbl_titulo_aviso": "Abisuaren Izenburua:",
        "lbl_fecha_inicio": "Hasiera Data:",
        "lbl_frecuencia_repeticion": "Errepikapen Maiztasuna:",
        "lbl_dias_margen": "Aktibo irauten duen egunak (marjina):",
        "lbl_de": "Nondik:",
        "lbl_a": "Nora:",
        "lbl_resumen_tarea": "Laburpena / Lana:",
        "ph_resumen": "Lanaren laburpen laburra...",
        "lbl_gestion_avisos": "⚠️ ABIZU ERREPIKAKORREN KUDEAKETA",
        "lbl_inicio": "Hasiera:",
        "lbl_repetir": "Errepikatu:",
        "lbl_duracion": "Iraupena:",
        "lbl_lista_pendientes": "EGITEKE DAUDENEN ZERRENDA",
        "lbl_ultimas_intervenciones": "📋 Azken Esku-hartzeak",
        "lbl_distribucion": "📊 Banaketa",
        "lbl_procesando_pdf": "Irudiak prozesatzen eta dokumentua sortzen...\nItxaron mesedez.",
        "freq_anual": "Urterokoa", "freq_semestral": "Seihilekoa", "freq_trimestral": "Hiruhilekoa",
        "freq_mensual": "Hilekoa", "freq_semanal": "Astekoa", "freq_diario": "Egunerokoa",
        "title_error": "Errorea",
        "title_actualizado": "Eguneratua",
        "title_nueva_version": "🚀 Bertsio berria eskuragarri",
        "title_region_cambiada": "Eskualdea Aldatuta",
        "title_pais_cambiado": "Herrialdea Aldatuta",
        "title_atencion": "Arreta",
        "title_backup_completo": "Babeskopia Osoa",
        "title_error_backup": "Errorea Babeskopian",
        "title_restaurar_copia": "Berrezarri Babeskopia",
        "title_seleccionar_backup": "Hautatu Babeskopia",
        "title_restauracion": "Berrezarpena",
        "title_error_restauracion": "Errorea Berrezartzean",
        "title_exportar_csv": "Esportatu CSV-ra",
        "title_exportado": "Esportatuta",
        "title_falta_libreria": "Liburutegia falta da",
        "title_logo_actualizado": "Logoa Eguneratuta",
        "title_logo_borrado": "Logoa Ezabatuta",
        "title_informacion": "Informazioa",
        "title_error_db": "DB Errorea",
        "title_exito": "Arrakasta",
        "title_error_pdf": "PDF Errorea",
        "title_limpieza": "Garbiketa",
        "title_acerca_de": "MantPro-ri buruz",
        "title_borrar_aviso": "Ezabatu Abisua",
        "title_confirmar_eliminacion": "Berretsi Ezabatzea",
        "title_confirmar_borrado": "Berretsi Ezabatzea",
        "title_error_fatal": "Errore Konponezina 💥",
        "title_seleccionar_carpeta_pdf": "Hautatu Karpeta PDFak Gordetzeko",
        "msg_error_conexion_github": "Ezin izan da GitHub-ekin konektatu eguneraketak bilatzeko.",
        "msg_ya_actualizado": "✅ Dagoeneko azken bertsioa instalatuta daukazu (v{v}).",
        "msg_nueva_version_disponible": "{actual} bertsioa instalatuta daukazu eta GitHub-en dagoeneko {nueva} dago.",
        "msg_quieres_descargar": "Orain deskargatu nahi duzu?",
        "btn_descargar": "Deskargatu",
        "btn_luego": "Geroago",
        "msg_region_cambiada": "Herrialdea: Espainia\nZonalde berria: {zona}\n(Jaiegun nazionalak, {parent}-koak eta {prov}-koak deskargatuko dira)",
        "msg_pais_cambiado": "Herrialde berria: {pais}\n({pais}-ko jaiegun nazionalak deskargatuko dira)",
        "msg_falta_resumen": "Laburpena falta da",
        "msg_backup_guardado": "Babeskopia garbia eta gordea:\n{archivo}",
        "msg_advertencia_restaurar": "⚠️ KONTUZ ⚠️\n\nBerrezartzean, uneko datu guztiak GAINIDATZIKO dira.\nJarraitu?",
        "msg_sistema_restaurado": "✅ Sistema ondo berrezarri da.",
        "msg_zip_corrupto": "ZIP hondatuta:\n{error}",
        "msg_csv_guardado": "CSV ondo gorde da.",
        "msg_instalar_xlsxwriter": "Instalatu: pip install xlsxwriter",
        "msg_excel_guardado": "Excel ondo gorde da.",
        "msg_logo_actualizado": "✅ Logoa eguneratuta. Hurrengo PDF-an agertuko da.",
        "msg_logo_borrado": "🗑️ Logoa sistematik ezabatu da.",
        "msg_sin_logo": "Ez zegoen logorik konfiguratuta.",
        "msg_fotos_basura": "{n} zabor-argazki daude. Ezabatu?",
        "msg_confirmar_borrar_aviso": "Ziur zaude abisu errepikakor hau behin betiko ezabatu nahi duzula?",
        "btn_si": "BAI",
        "btn_no": "EZ",
        "msg_confirmar_eliminacion_registro": "Erregistroa behin betiko ezabatu?\nArgazki erantsirik badu, diskotik ezabatuko da.\n\nDuela gutxiko prebentzio-lan bat bada, EGITEKE gisa markatuko da berriro.",
        "msg_confirmar_borrar_pendiente": "Ziur zaude egiteke dagoen lan hau ezabatu nahi duzula?",
        "msg_error_fatal": "Programak huts egin du. Sakatu 'Show Details' zergatia ikusteko:",
        "title_visor_imagen": "Irudi Ikustailea",
        "title_visor_manual": "📸 ESKUZKO IKUSTAILEA",
        "title_sincronizar_movil": "Sinkronizatu Mugikorra",
        "title_gestion_dias_especiales": "Egun Berezien Kudeaketa",
        "title_seleccionar_pais": "Hautatu Herrialdea",
        "title_seleccionar_provincia": "Hautatu Probintzia",
        "title_editar_registro": "Editatu Erregistroa",
        "title_editar_tarea_pendiente": "Editatu Egiteke Dagoen Zeregina",
        "title_editar_aviso": "✏️ Editatu Abisu Errepikakorra",
        "title_exportar_pdf": "Esportatu PDFra",
        "title_control_mantenimiento": "Mantentze Kontrola",
        "title_generando_pdf": "PDFa sortzen...",
        "tag_urgente": "Premiazkoa",
        "tag_electrico": "Elektrikoa",
        "tag_mecanico": "Mekanikoa",
        "tag_preventivo": "Prebentziozkoa",
        "lbl_avisos_pendientes": "Egiteke dauden Abisuak",
        "lbl_tareas_por_hacer": "Egiteko Zereginak",
        "lbl_registros_este_mes": "Erregistroak Hilabete Honetan",
        "hdr_estado": "Egoera",
        "hdr_titulo": "Izenburua",
        "hdr_frecuencia": "Maiztasuna",
        "hdr_proxima": "Hurrengoa",
        "hdr_sit": "Egoera",
        "lbl_opciones_exportacion": "Esportazio Aukerak",
        "lbl_exportar_todo": "Esportatu historia OSOA",
        "lbl_exportar_rango": "Esportatu data tartea",
        "lbl_exportar_por_mes": "Esportatu PDF bat hilabeteko",
        "lbl_incluir_imagenes": "📸 Sartu irudiak PDFan",
        "lbl_crear_nuevo_aviso": "Sortu Abisu Berria",
        "ph_titulo_aviso": "Abisuaren izenburua...",
        "ph_buscar_texto": "🔍 Bilatu testua (Motorra, Ihesa, KM1)...",
        "lbl_nuevo_trabajo": "Lan Berria",
        "ph_titulo": "Izenburua",
        "ph_detalles": "Xehetasunak",
        "lbl_acciones": "Ekintzak",
        "ph_otros_tags": "Beste etiketa batzuk...",
        "ph_otras_etiquetas": "Beste etiketa batzuk (komez banatuta)...",
        "msg_registro_guardado": "✅ Erregistroa ondo gorde da",
        "msg_tarea_completada": "✅ '{titulo}' zeregina osatuta",
        "msg_guardado_historial": "✅ Historian gordeta: {titulo}",
        "msg_eliminado_historial": "🗑️ Historiatik ezabatuta: {titulo}",
        "msg_pendiente_actualizado": "✅ Egiteke dagoena eguneratuta",
        "msg_mostrando_resultados": "🔍 {n} emaitza erakusten",
        "lbl_arrastra_foto": "Arrastratu argazkia hona\nedo sakatu bilatzeko",
        "lbl_formato_invalido": "Formatu baliogabea",
        "lbl_arrastra_despues": "Arrastratu ONDORENGO argazkia hona",
        "lbl_arrastra_click": "Arrastratu edo klik egin",
        "msg_error_cargar_imagen": "Errorea irudia kargatzean",
        "msg_es_carpeta": "📁 Karpeta bat da",
        "msg_no_imagen_valida": "❌ Ez da baliozko irudia",
        "title_seleccionar_logo": "Hautatu Logoa",
        "title_guardar_pdf": "Gorde PDFa",
        "title_exportar_excel": "Esportatu Excelera",
        "lbl_info": "Info",
        "btn_aceptar": "Onartu",

        # --- Usuarios, login y autoría de trabajos ---
        "hdr_realizado_por": "NORK EGINA",
        "menu_usuarios": "👥 Erabiltzaileen kudeaketa",
        "menu_cambiar_password": "🔑 Aldatu nire pasahitza",
        "msg_solo_admin": "Administratzaile batek soilik kudea ditzake erabiltzaileak.",
        "login_titulo": "MantPro — Sarrera",
        "login_usuario": "Erabiltzailea",
        "login_password": "Pasahitza",
        "login_entrar": "Sartu",
        "login_vacio": "Sartu erabiltzailea eta pasahitza.",
        "login_error": "Erabiltzailea edo pasahitza okerra.",
        "login_cambio_requerido": "Sartzeko pasahitza aldatu behar duzu.",
        "salir": "Irten",
        "cerrar": "Itxi",
        "aviso": "Oharra",
        "ok": "Eginda",
        "password_titulo": "Aldatu pasahitza",
        "password_obligatorio": "Zure lehen sarrera da: ezarri pasahitz berri bat.",
        "password_actual": "Uneko pasahitza",
        "password_nueva": "Pasahitz berria",
        "password_repetir": "Errepikatu",
        "password_no_coincide": "Pasahitzak ez datoz bat.",
        "usuarios_titulo": "Erabiltzaileen kudeaketa",
        "usuarios_col_login": "Erabiltzailea",
        "usuarios_col_nombre": "Izena",
        "usuarios_col_rol": "Rola",
        "usuarios_col_estado": "Egoera",
        "usuarios_col_acceso": "Azken sarrera",
        "rol_admin": "Administratzailea",
        "rol_tecnico": "Teknikaria",
        "activo": "Aktibo",
        "inactivo": "Inaktibo",
        "usuarios_forzar_cambio": "Eskatu aldaketa sartzean",
        "usuarios_anadir": "➕ Gehitu",
        "usuarios_reset": "🔑 Berrezarri pasahitza",
        "usuarios_cambiar_rol": "🎚 Aldatu rola",
        "usuarios_activar": "🚫 Gaitu / Desgaitu",
        "usuarios_selecciona": "Hautatu erabiltzaile bat zerrendatik.",
        "filtro_todos": "Guztiak",
        "lbl_sin_asignar": "Esleitu gabe",
        "lbl_ver_de": "Ikusi honenak",
        "lbl_asignar_a": "Esleitu honi",
        "btn_reasignar": "👤 Berresleitu",
    },
}

# Idioma activo en memoria (se carga desde la BD al arrancar la app)
_idioma_actual = "es"


def set_idioma(codigo):
    """Establece el idioma activo en memoria (no toca la base de datos)."""
    global _idioma_actual
    if codigo in TRADUCCIONES:
        _idioma_actual = codigo
    else:
        _idioma_actual = "es"


def get_idioma():
    return _idioma_actual


def t(clave):
    """Devuelve el texto traducido para 'clave' en el idioma activo.
    Si falta en el idioma activo, cae a español. Si tampoco existe, devuelve la propia clave."""
    dic_actual = TRADUCCIONES.get(_idioma_actual, TRADUCCIONES["es"])
    if clave in dic_actual:
        return dic_actual[clave]
    return TRADUCCIONES["es"].get(clave, clave)


# --------------------------------------------------------------------
# NORMALIZADOR DE FRECUENCIAS DE AVISOS RECURRENTES
# --------------------------------------------------------------------
# Las avisos recurrentes guardan en la base de datos el TEXTO que se veía
# en el combo "Frecuencia de Repetición" en el momento de crear/editar el
# aviso (p.ej. "Anual" si la interfaz estaba en español, "Yearly" si estaba
# en inglés). Toda la lógica de cálculo de recurrencia compara ese texto
# contra los literales fijos en español ("Diario", "Semanal", ...), así que
# si un aviso se guardó en otro idioma, dejaba de reconocerse.
#
# Esta función traduce CUALQUIER valor guardado, en CUALQUIER idioma
# conocido, de vuelta a su forma canónica en español, para que las
# comparaciones `freq == "Anual"` etc. sigan funcionando pase lo que pase.
_CLAVES_FRECUENCIA = ["freq_diario", "freq_semanal", "freq_mensual", "freq_trimestral", "freq_semestral", "freq_anual"]

def normalizar_frecuencia(valor):
    """Dado un valor de frecuencia guardado (en cualquier idioma soportado),
    devuelve su forma canónica en español ('Diario', 'Semanal', 'Mensual',
    'Trimestral', 'Semestral' o 'Anual'). Si no se reconoce, se devuelve tal cual."""
    if not valor:
        return valor
    for clave in _CLAVES_FRECUENCIA:
        for idioma in TRADUCCIONES:
            if TRADUCCIONES[idioma].get(clave) == valor:
                return TRADUCCIONES["es"][clave]
    return valor
